examples/hello/src/hello/app.nix
With doCheck enabled, the default package is likely to be built/cached by
cache.nixos.org already.
=> Match upstream

flake.nix
comparing with the more limited build.system caused a key collision in the attrset
=> Default system is musl

README.md
The previous example doesn’t work anymore.
=> Fix the example in README.md

cells/std/cli/flake.go, cells/std/cli/main.go, cells/std/cli/tui.go
Replace log.Fatal when fatal loading error occurs with propagating error
to main() so that Bubbletea can properly tear down UI and restore
terminal to its original state. Output the error after it's done.
=> tui: Tear down UI on loading error

flake.nix
when there is more than one layer of soil.
Note that this should also allow to merge `grow` and `growOn`
into a single function if so desired.
=> Avoid multiple eval of `grow args` in `growOn`

src/grow.nix
std used to overwrite nixpkgs input with its own even if it's provided.
Switch to adding nixpkgs input only if it is provided by flake and only with the one provided by flake.
=> Don't overwrite flake's nixpkgs input

src/clades.nix
Does the `\n` work on your system?
- the issue output:
```
> /nix/store/llj15iriibhfibss9jy46fpk6ss1kwfh-explore: line 17: syntax error near unexpected token `|'  
> /nix/store/llj15iriibhfibss9jy46fpk6ss1kwfh-explore: line 17: `|'
```
=> fix syntax error of data expo

cells/std/devshellProfiles.nix
It seems we can not render the table/list when mdbook-kriki enabled.
=> fix mdbook-krioki command

direnv_lib.sh
When I made the suggested shellcheck change I didn't realize that mapfile was incompatible with the default version of Bash (v3) running on OSX.
In this case I think it is more important to optimize for UX of developers on a highly popular OS than it is to cover every recommended lint extensively.
=> direnv: fix for darwin

.github/workflows/nix-darwin.yaml, .github/workflows/nix-linux.yaml, cells/std/packages.nix, cells/std/packages/adrgen.nix, cells/std/packages/mdbook-kroki-preprocessor.nix
- downstream `adrgen` package from nixpkgs, bump to latest master with https://github.com/asiermarques/adrgen/pull/14 that fixes build on Darwin with Go 1.18
- pass `Security` framework as build input for `mdbook-kroki-preprocessor`
- verify `default` devshell on CI
=> devshell: Fix for Darwin

cells/std/lib/default.nix, cells/std/lib/writeShellEntrypoint.md, cells/std/lib/writeShellEntrypoint.nix, docs/SUMMARY.md, docs/reference/std/lib/writeShellEntrypoint.md
- implemets an interface to produce OCI-images with the following
contracts:
```
/bin/entrypoint
/bin/debug
/bin/live
/bin/ready
```
=> imp: add standardized writeShellEntrypoint

src/validators.nix
Previously, if a user still had any references to an old revision of standard in their lock file, the types defined using that standard would fail to evaluate due to the recent rename. 
This allows the old type to properly evaluate with yants while informing the user that downstream may need to update their flake.
Originally outlined in this comment: https://github.com/divnix/std/issues/116#issuecomment-1242295250
=> properly deprecate the organelle type

README.md, flake.nix, src/harvest.nix, src/winnow.nix
After starting #126, I realized all that was needed was to modify harvest to allow for skipping marked derivations based on a predicate. Winnow is the same function as harvest, except it accepts a filter as it's first argo.
=> harvest: derive harvest from more general function 

docs/SUMMARY.md, docs/reference/blocktypes/nomad-job-manifests-blocktype.md, flake.nix, src/blocktypes.nix, src/blocktypes/nomadJobManifests.nix
- feat: add nomad job manifest block type
- refactor: complement nomadJobManifests block type
- docs: add doc entry for nomad job manifests block type
supersedes #132 &mdash; since I couldn't modify with `gh pr checkout` workflow :smile:
=> nomad envs

.devcontainer.json, cells/_automation/containers.nix, cells/lib/ops.nix, cells/lib/ops/mkDevOCI.nix, cells/lib/ops/mkOperable.nix, cells/lib/ops/mkSetup.nix, cells/lib/ops/mkUser.nix, cells/lib/ops/writeShellEntrypoint.nix, dogfood.nix, flake.lock, flake.nix
This PR introduces support for generating container images that are compatible with [devcontainers](https://code.visualstudio.com/docs/remote/containers). It ingests a devshell and builds a compatible OCI image which can then be invoked as a devcontainer.
=> feat: adds mkDevOCI for generating devcontainers

.github/workflows/gh-pages.yaml
The book link keeps breaking because we didn't configure the cname in the action. This should take care of it.
=> book: fix deployed domain

src/grow.nix
Allows attribute names from a given block to depends on another block,
without triggering an infinite recursion error.
=> fix: lazier loading of cells blocks.

cells/presets/nixago/lefthook.nix
Otherwise commit can go through even though staged file are modified by `treefmt`.
Also removed unnecessary glob '*'.
=> fix(presets/lefthook): fail on treefmt changes

src/grow.nix
The docs mentioned that the special `nixpkgs` input could be configured with `nixpkgsConfig`, but no such option existed.
=> impl: `nixpkgsConfig`

cells/presets/nixago/lefthook.nix
workaround https://github.com/siderolabs/conform/issues/225
Also people very commonly use WIP commits before tidying up, so
allowing them is probably necessary if we want people not disabling
conform pre-commit hook.
Note that this does not affect CI that should ideally still fail on
WIP commits (TODO: run conform on CI).
=> feat(presets/lefthook): allow WIP and fixup! commit

src/grow.nix
ci register feature induced strict evaluation of cell
blocks, due to lists being strict in nix.
=> fix: restore lazy cell loading

src/grow.nix
=> fix: import nixpkgs from inputs instead

cells/std/cli/cli.go
Closes #198 
As of now, its implementation is similar to re-cache, with a few important differences:
- Stderr is printed
- It returns a nonzero exit code if it fails to evaluate
- It prints a success message if evaluation succeeds
=> feat: add a `check` subcommand to validate the repo

cells/std/cli/env.go, cells/std/cli/flake.go, cells/std/cli/main.go, cells/std/lib/default.nix, deprecation.nix, direnv_lib.sh, src/blocktypes/actions/build.nix, src/blocktypes/actions/run.nix, src/blocktypes/arion.nix, src/blocktypes/containers.nix, src/blocktypes/data.nix, src/blocktypes/devshells.nix, src/blocktypes/files.nix, src/blocktypes/installables.nix, src/blocktypes/microvms.nix, src/blocktypes/nixago.nix, src/blocktypes/nomadJobManifests.nix, src/blocktypes/runnables.nix, src/devshell-drv.nix, src/grow.nix, src/validators.nix
This will allow us to properly capture build dependencies for the action, allowing `divnix/std-action` to build them in the proper phase, also ensuring they get cached. This also fixes #203, where the calling `nix` on `self` strips the flake of its git information, making `self.rev` inaccessible.
Alternative to #202 which satisfies divnix/std-action#23
Already tested and working for the publish action, just need to finish converting the rest of the actions to this interface before moving out of draft.
=> feat(actions): pass the target into the actions

src/blocktypes/microvms.nix
The microvm doesn't need the run action.
=> fix: remove run action for microvm

src/blocktypes/actions/run.nix
```
λ std //cliche/entrypoints/example:run add 1 2
3
```
=> fix: pass args to runnables

.github/workflows/gh-pages.yaml, .github/workflows/nix-darwin.yaml, .github/workflows/nix-linux.yaml, src/grow.nix
it's a fast-paced world now-a-days...
We had a user that hit an unbound feedback loop strolling into an UX abyss on `nix 2.5`...
- 2.7 has `.default` over `defaultX` semantics
- 2.9, iirc, has the vital `__funtor` fix
=> fix: violently nudge the use of an up-to-date nix version

src/actions.nix
The latest nix-uncached provides a more efficient schema which allows us to make a single call and still query the entire dependency closure for each path passed.
This will now capture any uncached dependencies even for derivations which are typically built locally, such as a NixOS system.
Also includes a nice speedup thanks to async queries _a la_ divnix/nix-uncached#1
We may also stand a better chance of getting an implementation like this merged upstream:
https://github.com/NixOS/nix/pull/7587#issuecomment-1399970497
=> fix: make build proviso much more robust

cells/lib/ops/mkDevOCI.nix, cells/lib/ops/mkOCI.nix, cells/lib/ops/mkStandardOCI.nix
When images need more configuration than the default exposed options,
in most cases, it is concerned with n2c's 'config' iface.
To honor that reality, let's expose it.
While this adds two similar interfaces (options & config), in practice,
when people copy over examples they would only see:
```nix
{
config = /* snip */;
}
```
That is less confusing than the following.
This was also the semantic hickup that prompted this commit:
```nix
{
options.config = /* snip */;
}
```
=> feat: polish the mkOCI interface further by exposing oft-used 'config'

src/flakeModule.nix
This allows the module to be used in a situation where the caller consumes `inputs'.foo.cells` but does not use the std options to define its own outputs.
=> feat: allow flakeModule usage without growing anything

flake.lock, flake.nix, src/actions.nix, src/blocktypes/arion.nix, src/blocktypes/containers.nix, src/blocktypes/data.nix, src/blocktypes/devshells.nix, src/blocktypes/files.nix, src/blocktypes/installables.nix, src/blocktypes/microvms.nix, src/blocktypes/nixago.nix, src/blocktypes/nomadJobManifests.nix, src/blocktypes/runnables.nix, src/mkCommand.nix
BRAKING CHANGE: the action signature changed: `system` -> `currentSystem`
All ad-hoc actions must be made aware of this change per
this commit as `std` in the short term has lost its deprecation
infrastructure due to the refactoring to `pasiano`
=> refactor: actions must run under currentSystem; clarify that

cells/lib/ops/mkOCI.nix, cells/lib/ops/mkStandardOCI.nix, flake.lock, flake.nix, src/blocktypes.nix, src/blocktypes/containers.nix, src/blocktypes/proviso/publish.sh, src/blocktypes/proviso/skopeo-inspect.sh, src/mkCommand.nix
This lays the groundwork for more control over how we implement them.
Users can now set an arbitrary number of tags for an image and upload all the given tags. To specify tags, set `meta.tags` to a list of your desire tags in the arguments to `mkOCI` or `mkStandardOCI`. 
The first tag is special in that it is used as the tag checked in the proviso for existence. That way, one can use a Nix input hash as the first tag to only upload when the derivation inside the image actually changes, while still tagging the images that are uploaded with useful tags like the git revision.
If no tags are set, the default upstream tagging mechanism of nix2container is used.
=> feat: acquire ownership over container actions from n2c

cells/lib/ops/mkOCI.nix, cells/lib/ops/mkStandardOCI.nix, deprecation.nix
We don't want users to hit a situation where  they reference one of the legacy n2c APIs such as `imageTag` and get the wrong value.
Therefore, disallow `tag` & `meta.tags` from being set together, always set the first value in `meta.tags` to the legacy `tag` arg of nix2container's `buildImage` function, and warn the user of the deprecated interface when accessed.
=> fix: ensure old image tag api is consistent

cells/lib/ops/mkOCI.nix, cells/lib/ops/mkStandardOCI.nix
`recursiveUpdate` takes precedence on the right hand side, and does not merge lists, so the user can overwriting important options set by mk*OCI functions, and end up with a borked image. Instead make the options set by these functions take precedence, and allow `copyToRoot` to be merged cleanly from the one set in `options`.
=> fix: don't allow defining broken image

cells/lib/ops/mkOCI.nix
These don't work with the multitags and are a concatenation
of build & metadata in the same implementation.
The multitag feature surfaced these shortcomings and hence
we should remove these facilities to avoid people using
(and cementing usage of) a non-public api because of habit.
=> feat: remove the legacy copyTo contracts from n2c images

src/build-fetched-extractor.sed
"will be fetched" catches packages that are already cached, we need to
find those that aren't.
=> fix: build proviso needs to find uncached paths

cells/lib/ops/mkStandardOCI.nix
If the script is not `exec`ed, then it cannot properly respond to any
signals that might be meant for the main process.
=> fix: exec operable script

direnv_lib.sh
Prior to this change, if `$PWD` contains an `@` then the `nix build` fails due to nix being unable to guess the schema/type for the URL.
For example;
```console
$ cd /tmp/
$ git clone https://github.com/divnix/std.git @some_path
Cloning into '@some_path'...
remote: Enumerating objects: 7598, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 7598 (delta 57), reused 86 (delta 51), pack-reused 7495
Receiving objects: 100% (7598/7598), 5.49 MiB | 1.18 MiB/s, done.
Resolving deltas: 100% (4983/4983), done.
$ cd @some_path
$ direnv allow
direnv: loading /tmp/@some_path/.envrc
direnv: using std cells //_automation/devshells:default
direnv: Watching: cells/_automation/devshells.nix
direnv: Watching: cells/_automation/devshells …
```
=> fix: Specify type/schema for nix build in direnv integration

flake.lock, flake.nix
**Rationale**
[Preemptive maintenance in advance of Paisano refactor](https://github.com/paisano-nix/core/pull/15).
=> refactor: adopt paisano v0.1.0 api

.gitignore
On a fresh update of my local copy of the repo,
`.data/` was listed in the untracked files.
=> fix: add prj-spec dirs to gitignore

src/std/templates/rust/nix/repo/shells.nix, src/tests/checks.nix
This PR replaces previous behavior into symlink + replace whenever reload is triggered. This allows for success `direnv allow`.
```
% ❯ direnv allow
direnv: loading ~/local_repos/zork/.envrc                                                     
/nix/store/20izn153a86zz6wp3b1pbgf4hgvvvcz5-source
direnv: PRJ_ROOT:        /Users/hungtran/local_repos/zork
direnv: PRJ_ID:          none
direnv: PRJ_CONFIG_HOME: .config
direnv: PRJ_RUNTIME_DIR: .run
direnv: PRJ_CACHE_HOME:  .cache
direnv: PRJ_DATA_HOME:   .data
direnv: PRJ_PATH:        .bin
direnv: using envreload //repo/userShells/hungtran //repo/userShells/default //repo/userShells
direnv: Watching: nix/repo/userShells.nix
direnv: Watching: nix/repo/userShells.nix
direnv: Watching: nix/repo/userShells.nix
evaluating derivation …
```
=> fix(templates/rust): allow rust devshell startup to run 'direnv allow' multiple time, idempotently

src/lib/ops/mkStandardOCI.nix, src/local/flake.lock, src/tests/flake.lock
A bit of an advanced nix foo is to dectect argument definition not
by value, but by leveraging the way attrs function defaulting works:
In `args @ { foo ? null, ... }`, args only has an argument `foo`,
if foo was defined by the caller. `foo` would still be `null`, but
`args.foo` does not exist.
mkOCI leverages this to collate the two means by which an image
tag can be defined `args.tag` & `args.meta.tags`.
This fix passes on this relevant calling context from `mkStandardOCI`
down to `mkOCI` which will then correctly perform the checks and
collation of values.
Prior to this PR, a recent refactoring had produced a regression
where `mkOCI` had _always_ complained if the user had set `args.meta.tags`
due to that from the `mkOCI` perspective, `args.tag` was _also_
(erroneously) passed down …
=> fix(lib/ops): tag defaulting while forwarding mkStandardOCI to mkOCI

src/lib/ops/mkOperable.nix, tests/_snapshots/cells-lib-ops
fix: #318
Operables wrap packages, and then they are symlinked via `lib.getExe` into
the container.
```nix
/* Get the path to the main program of a derivation with either
meta.mainProgram or pname or name
Type: getExe :: derivation -> string
Example:
getExe pkgs.hello
=> "/nix/store/g124820p9hlv4lj8qplzxw1c44dxaw1k-hello-2.12/bin/hello"
getExe pkgs.mustache-go
=> "/nix/store/am9ml4f4ywvivxnkiaqwr0hyxka1xjsf-mustache-go-1.3.0/bin/mustache"
*/
getExe = x:
"${lib.getBin x}/bin/${x.meta.mainProgram or (lib.getName x)}";
```
Prior to this commit, using `package.name` (which is the wrong attribute, anyways),
we where furnishing that name to `/bin/<name>`.
While `lib.getBin` reads the store path verbatim and thereby honors that name,
`lib.getName` resolves differently via the following …
=> fix(lib/ops): ensure the getName contract is uphold for operables

src/lib/ops/mkDevOCI.nix
When working with Dev Containers, we are in the Dev X domain, where speed and "no-unexpected-warnings" matter.
- Avoid unexpected warnings by setting `accept-flake-config = true`; using flake level config is general practice in `std`-like projects where a Nix Power User provides an environment for team colleagues. The warnings are technically accurately motivated, but in practice just too noisy for these scenarios where the power user is trusted.
- `preLoadStorePaths: A list of store paths to preload/copy into the container.`: This helps speed things up. You can preload some store paths to make the loading of the dev container faster for the user (i.e. avoid lazy fetching during startup by already baking those paths into the image)
=> Improve the UX for mkDevOCI

src/lib/ops/mkDevOCI.nix, src/lib/ops/mkOCI.nix
fixes: #333 
It appears that putting those two stages together would result in the entrypoints being overwritten.
=> fix(ops/mkDevOCI): avoid undue symlink and improve ux

src/std/fwlib/blockTypes/kubectl.nix
The invocation of `icdiff` needs to be `-r`ecursive.
Furthermore, when `:diff` action is employed locally, server side apply would conflict (e.g. if `:apply` is reserved for a CI/CD actor) on field ownership and therefore may not be used.
=> fix(kubectl): diff action and differ command

.github/workflows/flakehub-publish-tagged.yml
If you're interested, you can publish existing tags using this updated workflow. Once this merges, you can go to the workflow on GitHub at https://github.com/divnix/std/actions/workflows/flakehub-publish-tagged.yml, click "Run workflow", and then type in -- for example -- `v0.24.0-1` or `v0.23.2`.
I hope that helps!
(also note that it'll automatically upload as divnix/std if it is published from divnix/std, no need to specify the `name` key if you don't want to 👍.)
=> FlakeHub: support uploading existing tags

flake.lock, flake.nix, tests/_snapshots/check-augmented-cell-inputs
https://github.com/divnix/std/pull/348 propones to add lib as a separate input on the basis of proper semantic distinction between `nixpkgs` and `lib`.
They only happen to be sourcable from the same input, but lib is a library extension of nix and not specific to nixpkgs.
Add `lib` as semantically distinct extra input.
https://github.com/divnix/std/pull/348 had some failing tests that this PR hopefully fixes.
=> fix: broken `lib` follows

flake.lock, flake.nix
In https://github.com/divnix/std/pull/349 we semantically sepratated `lib` from `nixpkg$`, however we didn't catch all follows.
- Finish the job
- `yants` already used `nixpkgs.lib`
- and so did `haumea`
=> chore: ensure a single lib input

src/lib/cfg/cog.nix
Is:
```
cocogitto     - A set of cli tools for the conventional commit and semver specifications
```
Want:
```
cog           - A set of cli tools for the conventional commit and semver specifications
```
- add the `name` attribute to the command option
=> fix: cocogitto cli name in devshell menu

src/std/fwlib/flakeModule.nix
For divnix/std#235, `std.grow.nixpkgsConfig` was made optional. However (at least in my config), `nixpkgsConfig` is not defined when it's checked for, even if it's set. Instead, I think setting a default of `{ }` should work - as far as I can tell, that's ultimately what it defaults to in nixpkgs.
=> Set default for nixpkgsConfig in flake-parts module

src/std/fwlib/blockTypes/kubectl.nix
While running apply and diff through `std` cli,
`kubectl` will produce an unexpected args error.
Put the filename arg after recursive,
so that it can be followed by a manifest path
=> Fix kubectl arguments order

src/local/flake.lock, src/std/fwlib/blockTypes/installables.nix, src/std/templates/rust/nix/repo/shells.nix, src/tests/flake.lock
https://github.com/divnix/std/issues/357
=> fix: quoting of PRJ_PATH/fragment for installables

src/std/fwlib/blockTypes/terra.nix
When terraform errors output the affected line-of-code the output is highly unreadable as `config.tf.json' is a one-line JSON file.
Since there seems to be no nix expression for pretty printing JSON, this PR uses `jq` on the command line instead.
The result is that terraform syntax errors output the single affected line-of-code.
=> fix: Improve readability of terraform errors

src/std/fwlib/blockTypes/kubectl.nix
Greetings @blaggacao, found a bug while using the blocktype kubectl, below is the explaination
In yaml (manifest), `metadata.labels` can be `null`
e.g.
```yaml
metadata:
labels:
```
or
```yaml
metadata:
labels: null
```
instead of the standard
```yaml
metadata:
labels: {}
```
Which cause the `dmerge` in `amendAlways` fails
```sh
error:
rigt-hand-side must be of the same type as left-hand-side
at 'metadata.labels':
- lhs: null @ undetectable posision
- rhs: set @ /nix/store/z6hf8dcim8qdgs0nh6bvf52x0w2zzkpf-incl/std/fwlib/blockTypes/kubectl.nix:62:21
```
Patch the edge case, with `manifest.metadata.labels = {};` before doing `dmerge` (now `lhs` will also be a set).
=> Fix metadata labels of manifest

src/local/flake.lock, src/std/fwlib/blockTypes/nixostests.nix, src/tests/flake.lock, tests/_snapshots/bt-blocktypes, tests/bt-blocktypes/expr.nix
- You may have a SDLC which runs nixos tests
- Especially if your deployment target is nixos
- Add nixostest block type
- Add iptable rules so that you can interact with the vm on your browser naturally
=> feat: add nixostests block type

src/data/configs/lefthook.nix, src/data/configs/treefmt.nix, src/lib/cfg/lefthook.nix
this helps with running hooks outside the devshell, for example:
- Jetbrains IDE's Commit dialog
for completeness' sake also updated all dependencies switching to direct paths instead of command invocations
=> fix: lefthook: run directly instead of (default) complex script

README.md
=> chore: fix typo on contribution instructions

src/lib/ops/mkStandardOCI.nix
I have found that uid and gid parameters in mkStandardOCI function was being ignored. I hope this fix will be enough.
=> fix uid/gid in OCI user

src/lib/ops/mkOCI.nix, src/lib/ops/mkSetup.nix, src/lib/ops/mkStandardOCI.nix
existing users of `config.copyToRoot` quite likely need to hove the contents of this key to `setup = [];` &mdash; `config.copyToRoot` may prime the nix2container permission cache with a parent folder (e.g. `/bin`) and conflicting permissions
=> fix!: oci perms

flake.lock, src/local/flake.lock, src/tests/flake.lock, tests/_snapshots/check-augmented-cell-inputs
fixes #385 - Broken `nix flake show` command.
update flake inputs:
- `flake.lock`
- `src/local/flake.lock`
- `src/tests/flake.lock`
update store paths in tests:
- `tests/_snapshots/check-augmented-cell-inputs`
=> fix: update flake & subflakes lockfiles, fix test

docs/reference/blocktypes.md, src/std/fwlib/blockTypes/nvfetcher.nix
Add sections to "Builtin Block Types" for each `blockType` without one.
Fixes: #386 (partially)
- Matches existing sections by inserting the contents of the file with the `blockType` definition.
- Fixes typo in comment in `blockTypes.nvfetcher` definition file.
If desired, I'd also like to:
I could do this in another PR if out of scope for this one.
=> docs: Add sections for missing `blockTypes`

.github/workflows/ci.yml, src/local/flake.lock, src/std/fwlib/actions/build-proviso.sh, src/std/fwlib/blockTypes/_postDiffToGitHubSnippet.nix, src/std/fwlib/blockTypes/kubectl.nix, src/std/fwlib/blockTypes/nvfetcher.nix, src/std/fwlib/blockTypes/terra.nix, src/tests/flake.lock, src/tests/flake.nix, tests/_snapshots/check-augmented-cell-inputs
Introduce `postDiffToGitHubSnippet` for unified diff posting and update `kubectl.nix` and `terra.nix`
- **Add `postDiffToGitHubSnippet`:**
- Created a reusable snippet that handles posting unified diffs to GitHub PR comments using the `gh` CLI.
- Manages existing comments by updating them or creates new ones if necessary.
- **Update `kubectl.nix`:**
- Replaced inline diff posting logic with the new `postDiffToGitHubSnippet`.
- **Modify `terra.nix`:**
- Integrated `postDiffToGitHubSnippet` into the `plan` command within the `wrap` function.
- Exported `TF_VAR_fragment` and `TF_VAR_fragmentRelPath` for use in Terraform configurations.
- Changed the Terraform working directory to `$PRJ_ROOT/.cache/${fragmentRelPath}/.tf` for better organization.
=> feat: make terra plan write diff to github PR

src/data/configs/treefmt.nix
make `prettier-plugin-toml` work again
=> fix: prettier toml plugin path

src/std/fwlib/blockTypes/nvfetcher.nix
As stated on the documentation.
> '' is escaped by prefixing it with one single quote (')
=> fix: balance nvfetcher script quotes

src/data/configs/lefthook.nix, src/lib/cfg/treefmt.nix
[nixpkgs@dcb250a](https://github.com/NixOS/nixpkgs/commit/dcb250aecc47ed727521bd9d62e23861e8b64bdf) introduced some changes to the `treefmt` package:
- the `treefmt` package is `treefmt v2` aka the go version)
- the `treefmt1` package throws an eval error
resulting in broken `std devens` as they trigger the eval error for `treefmt1`.
[std@febf2ee](https://github.com/divnix/std/commit/febf2ee06d6a5beeff1e1807e1348f497fffb14e) explicitly selects the discontinued rust implementation due to unfixed bugs in 24.11 for treefmt < 2.1.1.
The `std` repo still uses the `23.11` nixpkgs release.
@blaggacao I'm not sure what the best path forward is for this change to not break backwards compatibility, please advise.
Until this is sorted I'll leave this PR as draft for further discussion.
=> fix: treefmt on nixos-unstable
