cells/std/devshellProfiles.nix
making the shell commands clarify.
By the way, could you please add the filter to src of the CLI ? There is no reason to compile again when some code changed.
=> move some commands to optionals

cells/std/cli.nix
Do we need a simple github CI check?
=> fix vendorSha

cells/std/Readme.md, docs/explain/why-std.md, src/grow.nix, src/incl.nix
Hi, thanks for this interesting project! I just stumbled upon a few probable typos while reading and thought I'll send a quick PR.
=> fix(docs): typo in incl.nix

docs/SUMMARY.md, docs/reference/clades/containers-clade.md, flake.nix, src/clades.nix, src/clades/containers.nix
- This is a pretty common devops scenario (build & push an OCI-image)
- We are nice. Hence, we cover it ootb
=> imp: add container clade (nix2container)

direnv_lib.sh
There is still an issue where the time for a `nix build` is non-deterministic and takes far longer about 1/10 times, even if the evaluation is already fully cached, which will likely require a good solution for NixOS/nix#2913.
Since the issue is out of scope for `std`, I'm opening this PR anyway.
=> direnv: improve load speed and address shellcheck

cells/std/lib/default.nix, cells/std/lib/fromMicrovmWith.md, cells/std/lib/fromMicrovmWith.nix, docs/SUMMARY.md, docs/reference/clades/microvms-clade.md, flake.nix, src/clades.nix, src/clades/microvms.nix
=> Add microvm  clade

cells/std/cli/main.go
=> fix(std): satify the PRJ_ROOT contractual assumption

src/clades/installables.nix
https://github.com/ralismark/nix-appimage
=> clade: add bundleAppImage

src/validators.nix
Meant to include in #124 but I forgot to stage it.
=> better organelle deprecation message

src/blocktypes/nomadJobManifests.nix
A minor oversight of the Nomad manifests is that the deploy action did not check if an existing render was actually a render from the current revision.
This fixes that by checking the revision in the render against the current revision.
=> nomadJobManifests: check render revision

deprecation.nix, docs/SUMMARY.md, docs/reference/deprecations.md, flake.nix, src/grow.nix, src/validators.nix
=> feat: improve deprecation machinery

cells/std/cli.nix, cells/std/cli/go.mod, cells/std/cli/go.sum, cells/std/cli/keys/keys.go, cells/std/cli/tui.go, src/blocktypes/runnables.nix
=> feat: pass args to runnables

flake.lock
I pushed a little fix to devshell repo, would like to update it everywhere
=> Update devshell flake

cells/lib/ops/mkOCI.nix, cells/lib/ops/mkOperable.nix, cells/lib/ops/mkStandardOCI.nix, cells/lib/ops/mkUser.nix
Addresses some missed items from the recent refactor.
=> fix: fixes scoping issue after refactor

cells/lib/ops/mkDevOCI.nix
=> chore: add devshell env to mkDevOCI

cells/std/cli/cli.go
=> fix: target names with colons

cells/lib/dev.nix, cells/lib/dev/mkArion.md, cells/lib/dev/mkArion.nix, docs/SUMMARY.md, docs/reference/blocktypes/arion-blocktype.md, docs/reference/lib/dev/mkArion.md, flake.nix, src/blocktypes.nix, src/blocktypes/arion.nix
=> feat: add arion (docker-compose) blocktype

book.toml, cells/lib/dev/mkShell.nix, src/blocktypes/actions/build.nix
- style: treefmt
- fix: flip-flop side-effect where treefmt battles nixago autogeneration
=> fix flipflop

README.md, dogfood.nix, flake.nix, src/pick.nix
=> feat: add pick function

.editorconfig, cells/presets/nixago/editorconfig.nix, cells/std/nixago/editorconfig.nix
=> fix(std): nixago editorconfig special ini format

src/grow.nix
Would be better: https://github.com/NixOS/nixpkgs/pull/203999
=> feat: render nix config into a string

README.md, cells/std/packages.nix, cells/std/packages/mdbook-kroki-preprocessor.nix, flake.lock, flake.nix
=> refactor: rm kroki preprocessor from flake inputs

src/blocktypes.nix, src/blocktypes/actions/build.nix, src/blocktypes/arion.nix, src/blocktypes/containers.nix, src/blocktypes/data.nix, src/blocktypes/devshells.nix, src/blocktypes/files.nix, src/blocktypes/functions.nix, src/blocktypes/installables.nix, src/blocktypes/microvms.nix, src/blocktypes/nixago.nix, src/blocktypes/nomadJobManifests.nix, src/blocktypes/runnables.nix, src/grow.nix, src/validators.nix
=> refactor: require action commands to be derivations

src/blocktypes.nix, src/blocktypes/actions/build.nix, src/blocktypes/containers.nix, src/blocktypes/nomadJobManifests.nix, src/grow.nix
A proviso is an optional condition for a given action which std-action can use to determine if a job actually needs to run in a given CI iteration, saving work if not.
Proviso should be free from context unless there is absolutely no workaround, and they should be idempotent, at least in a pragmantic sense.
linked with divnix/std-action#28
~~Will take out of draft after I implement a proviso for OCI image publishing and nail down the spec.~~ done
=> feat(ci): add proviso for build

src/blocktypes.nix, src/blocktypes/actions/build.nix, src/grow.nix
This value is rightfully coupled to what is actually placed in the action script.
=> fix: allow overriding the targetDrv

flake.nix, src/flakeModule.nix
closes: #224
@roberth @dermetfan can you have a look at this?
=> feat: impl flake parts module

.github/workflows/ci.yml, .github/workflows/gh-pages.yaml, .github/workflows/nix-darwin.yaml, .github/workflows/nix-linux.yaml, .github/workflows/std.yml, dogfood.nix
Also includes Mac builds so that our cache is popullated for Mac users.
=> Initiate Standard Action

src/blocktypes/microvms.nix
```
std //guangtao/microvms/dev:run               
char device redirected to /dev/pts/10 (label con0)
checking /dev/vdb...
[fsck.ext4 (1) -- /mnt-root/var] fsck.ext4 -a /dev/vdb
/dev/vdb: recovering journal
/dev/vdb: clean, 60/131072 files, 30342/524288 blocks
<<< NixOS Stage 2 >>>
running activation script...
reviving group 'dhcpcd' with GID 999
reviving group 'nscd' with GID 998
```
=> imp: enrich the microvm command set

docs/SUMMARY.md, docs/reference/blocktypes/pkgs-blocktype.md, src/blocktypes.nix, src/blocktypes/pkgs.nix, src/grow.nix, src/validators.nix
=> feat: exclude specific block types from extraction

cells/lib/ops/mkOperableScript.nix
An atribute set makes single flag arguments awkward to declare, and no specific order is guaranteed, meaning that programs that require args in a particular order will fail.
In order to use the style which is most natural for the given program and to keep the resulting script readable, users can group key=value style arguments in a true attribute set, or several arguments of the same class in a list; i.e:
```nix
mkOperableScript {
args = [
"--single-flag"
{"--port" = 80;}
["path/a" "path/b" "path/c" ["path/with" "spaces"]]
];
}
```
results in:
```bash
args+=("--single-flag")
args+=("--port" "80")
args+=("path/a" "path/b" "path/c" "path/with spaces")
```
For the sake of backward compatibility, the previous API is retained in the event that an attribute set is passed instead of a list.
=> fix: mkOperableScript needs args list

src/flakeModule.nix
This is another attempt at fixing #272.
~Unfortunately, it looks like there might be another issue uncovered after fixing the initial issue. When using the flake module, I now get this error:~
Also fixed:
```console
error: value is a function while a set was expected
at /nix/store/l63z3fk6bx37iprrxwgwbzxn55xh0dx3-source/src/flakeModule.nix:69:36:
68|
69|     cellBlocksType = mkOptionType {
|                                    ^
70|       name = "cellBlocks";
(use '--show-trace' to show detailed location information)
```
=> fix: prevent flake-parts module scope collision of `types` variables

flake.lock
=> fix(tui): load fixed paisano tui

src/actions.nix, src/blocktypes/containers.nix, src/build-fetched-extractor.sed, src/build-filter.jq
- fix: use nix-uncached with optimizations and fixes
- fix: query correct targets for uncached items
=> fix build proviso

README.md
Fix the Github search query link
=> Fix GitHub search query

PITCH.md
the `:heart_eyes:` emojis are specific to github and shows up as plain text on the website
=> docs: fix emojis in mdbook

cells/lib/ops/mkStandardOCI.nix
adding /tmp and certs for scoring in a higher bucket of the frequenctly-required-by-users histogram (armchair estimate / educated guess)
set up linux pam files for the nobody / nogroup user
=> feat: improve std image

docs/reference/blocktypes.md, flake.lock, flake.nix, src/local/flake.lock, src/std/fwlib/blockTypes/terra.nix, src/tests/flake.lock, tests/_snapshots/bt-blocktypes, tests/_snapshots/check-augmented-cell-inputs, tests/bt-blocktypes/expr.nix
- feat(blocktypes): add terra
closes: #234
=> Terranix Blocktype

src/std/fwlib/blockTypes/kubectl.nix
The `kubectl` was &mdash; until now &mdash; only a stump implementation in the interest of advancing the feature.
This PR iterated over a real-world deployment making use of `kustomize` and thereby finalized the `kubectl` just out of a PoC / sketch.
Further iteration to be expected.
=> fix(blockTypes/kubectl): fix and adapt for use with kustomize

src/std/fwlib/blockTypes/kubectl.nix
For a change to remote state, a reviewer may do a process audit or a result audit.
A process audit requires the entire context of the rendering routine loaded in every detail as a prerequisite of the audit.
A result audit, in turn, requires only context of the data description language and the api being mutated.
Therefore, a result audit is more ergonomic in many instances, and thus, more effective and reliable.
This PR implements the feature of posting a comment with the expected `kubectl` diff to the PR, if the required environment
variables are being set (see [code](https://github.com/divnix/std/pull/343/files#diff-fbb46dfd8e991a604cdef521e0116b14f45e1e7357d6c12d16d550bca66992c7R135)) for example in GitHub actions and if `gh` binary is detected in the environment.
Note: similar …
=> feat(kubectl): publish diff if on github ci as PR comment

.github/workflows/gh-pages.yaml, docs/guides/envrc.md, docs/reference/blocktypes.md, docs/tutorials/hello-moon/Readme.md
Hopefully this ticks all CI steps now :)
=> chore(ci): Fix gh pages deployment

dogfood.nix, flake.lock, flake.nix, src/local/flake.lock, src/tests/flake.lock, tests/_snapshots/check-augmented-cell-inputs
- feat: update paisano core w/ growOn registry list merge improvement
- feat: upd paistano tui with some a fix on targets w/ dots in the name
=> Update Paisano (core/tui)

flake.lock, flake.nix, src/local/flake.lock, src/tests/flake.lock, tests/_snapshots/check-augmented-cell-inputs, tests/_snapshots/flake-module
- allows to mark actions as requiring arguments
- improves the paisano output handling
- https://github.com/paisano-nix/tui/pull/9
- https://github.com/paisano-nix/core/pull/18
=> feat: use new paisano features
